source 'https://rubygems.org'


gem 'rails', '~> 4.1.4'
gem 'cocoon'
gem 'will_paginate', '3.0.4'
gem 'bootstrap-will_paginate', '0.0.9'
gem 'bootstrap-sass', '2.3.2.0'
gem 'sass-rails', '~> 4.0.0'
gem 'bcrypt-ruby', '3.1.2'
# gem 'pg', '0.15.1'
gem 'sqlite3', '1.3.8' 
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'haml'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'carrierwave'
gem 'mini_magick'
gem 'ckeditor'
gem 'annotate'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'state_machine'
gem 'factory_girl_rails'
gem 'faker'
gem 'draper'
gem 'date_validator'
gem 'ransack', '1.2.3'
gem 'devise'
gem 'activeadmin', github: 'gregbell/active_admin'
gem 'kaminari'
gem 'cancancan', '~> 1.9'
